name = "Kiera Github"
license = "MIT"
licenselink = "https://github.com/jgornick/hugo-kiera-github/blob/master/LICENSE.md"
description = "Hugo Theme for creative and technical writing"
homepage = "http://github.com/jgornick/hugo-kiera-github"
tags = ["blog","minimal","responsive"]
features = ["blog","disqus","google-analytics","font-awesome"]
min_version = "0.30.2"

[author]
  name = "b. avianto"
  homepage = "http://avianto.com/"
